# Branch protection rules for main and dev branches
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "poe check"
          - "poe test"
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      enforce_admins: true
      restrictions: null
  - name: dev
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "poe check"
          - "poe test"
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      enforce_admins: true
      restrictions: null
