# Branch protection rules for main branch
branch_protection_rules:
  - branch: main
    required_status_checks:
      strict: true
      contexts:
        - "Run Code Checks"
    enforce_admins: true
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
    restrictions: null
