version: '3.8'

services:
  # Java validation environment
  java-validator:
    build:
      context: .
      dockerfile: docker/Dockerfile.java
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./migration-output:/app/migration-output
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://migration_user:migration_password@mongodb:27017/migrationdb
    depends_on:
      - mongodb
    networks:
      - migration-network

  # MongoDB database
  mongodb:
    build:
      context: .
      dockerfile: docker/Dockerfile.mongodb
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=migrationdb
    ports:
      - "27017:27017"
    networks:
      - migration-network

  # Service for running the migration agent
  migration-agent:
    build:
      context: .
      dockerfile: docker/Dockerfile.agent
    volumes:
      - ./src:/app/src
      - ./migration-output:/app/migration-output
      - .:/app/repo
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REPO_PATH=/app/repo
    depends_on:
      - mongodb
    networks:
      - migration-network

networks:
  migration-network:
    driver: bridge

volumes:
  mongodb-data: 