name: PR Checks

on:
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]

jobs:
  check:
    name: Run Code Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run poe check
        run: poetry run poe check

      - name: Run poe test
        run: poetry run poe test

      - name: Upload code summary
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: code-summary
          path: code_base_summary.json
          if-no-files-found: error
