name: Pull Request Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check:
    name: Run Code Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run code checks
        run: |
          poe check

      - name: Upload code summary
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: code-summary
          path: code_base_summary.json
          if-no-files-found: error
